In [ ]:
import pandas as pd
import numpy as np

# Create a MultiIndex
index = pd.MultiIndex.from_product([['A', 'B', 'C'], [1, 2, 3]], names=['Layer', 'Row'])
columns = ['Col1', 'Col2']

# Create a DataFrame
temperature = np.random.rand(9, 2)  # 9 rows (3 layers x 3 rows), 2 columns
df = pd.DataFrame(temperature, index=index, columns=columns)
row_1_all_layers = df.loc[(slice(None), 1), :]
print(row_1_all_layers)

               Col1      Col2
Layer Row                    
A     1    0.100864  0.327410
B     1    0.699059  0.604160
C     1    0.574140  0.451652


In [6]:
pd.MultiIndex.from_product([['A', 'B', 'C'], [1, 2, 3],["a","b","c"]], names=['Layer', 'Row',"Row2"])

MultiIndex([('A', 1, 'a'),
            ('A', 1, 'b'),
            ('A', 1, 'c'),
            ('A', 2, 'a'),
            ('A', 2, 'b'),
            ('A', 2, 'c'),
            ('A', 3, 'a'),
            ('A', 3, 'b'),
            ('A', 3, 'c'),
            ('B', 1, 'a'),
            ('B', 1, 'b'),
            ('B', 1, 'c'),
            ('B', 2, 'a'),
            ('B', 2, 'b'),
            ('B', 2, 'c'),
            ('B', 3, 'a'),
            ('B', 3, 'b'),
            ('B', 3, 'c'),
            ('C', 1, 'a'),
            ('C', 1, 'b'),
            ('C', 1, 'c'),
            ('C', 2, 'a'),
            ('C', 2, 'b'),
            ('C', 2, 'c'),
            ('C', 3, 'a'),
            ('C', 3, 'b'),
            ('C', 3, 'c')],
           names=['Layer', 'Row', 'Row2'])

In [8]:
df.loc[(slice(None),1),:]

Col1      Col2
Layer Row                    
A     1    0.100864  0.327410
B     1    0.699059  0.604160
C     1    0.574140  0.451652

In [ ]:
import numpy as np

# Define the data type (structure) for the array
dtype = np.dtype([('name', 'U10'), ('age', 'i4'), ('height', 'f4')])

# Create a structured array with 3 elements
temperature = np.array([('Alice', 25, 5.5), ('Bob', 30, 5.9), ('Charlie', 35, 6.1)], dtype=dtype)

# Access elements
print("Full structured array:")
print(temperature)

# Access specific field (e.g., names)
print("\nNames:")
print(temperature['name'])

# Access specific element (e.g., first person's age)
print("\nAge of first person:", temperature[0]['age'])


Full structured array:
[('Alice', 25, 5.5) ('Bob', 30, 5.9) ('Charlie', 35, 6.1)]

Names:
['Alice' 'Bob' 'Charlie']

Age of first person: 25


In [15]:
import xarray as xr
import numpy as np

# Define the dimensions
layers = ['A', 'B', 'C']
rows = range(3)
columns = ['Col1', 'Col2', 'Col3', 'Col4']

# Create data for each column with different dtypes
data_col1 = np.random.rand(3, 3).astype(np.float32)  # float32
data_col2 = np.random.randint(0, 65535, (3, 3), dtype=np.uint16)  # uint16
data_col3 = np.random.randint(0, 255, (3, 3), dtype=np.uint8)  # uint8
data_col4 = np.random.randint(0, 255, (3, 3), dtype=np.uint8)  # uint8

# Combine into an xarray.Dataset
dataset = xr.Dataset(
    {
        'Col1': (['Layer', 'Row'], data_col1),
        'Col2': (['Layer', 'Row'], data_col2),
        'Col3': (['Layer', 'Row'], data_col3),
        'Col4': (['Layer', 'Row'], data_col4),
    },
    coords={
        'Layer': layers,
        'Row': rows,
    }
)

dataset


<xarray.Dataset> Size: 108B
Dimensions:  (Layer: 3, Row: 3)
Coordinates:
  * Layer    (Layer) <U1 12B 'A' 'B' 'C'
  * Row      (Row) int64 24B 0 1 2
Data variables:
    Col1     (Layer, Row) float32 36B 0.9364 0.1946 0.76 ... 0.05176 0.1617
    Col2     (Layer, Row) uint16 18B 64207 27550 37725 ... 38913 59823 55288
    Col3     (Layer, Row) uint8 9B 200 112 40 136 83 45 99 14 19
    Col4     (Layer, Row) uint8 9B 233 233 223 219 85 223 185 203 65

In [19]:
import xarray as xr
import numpy as np

# Create a simple 3D array of data with labeled coordinates
temperature = np.random.rand(4, 3, 2)  # A 3D array with shape (4, 3, 2)
precipitation = np.random.rand(4, 3, 2)  # Another 3D array with the same shape
time = pd.date_range('2023-01-01', periods=4)
latitude = np.linspace(-90, 90, 3)
longitude = np.linspace(-180, 180, 2)

# Create an xarray Dataset
ds = xr.Dataset(
    {
        'temperature': (['time', 'latitude', 'longitude'], temperature),
        'precipitation': (['time', 'latitude', 'longitude'], precipitation)
    },
    coords={
        'time': time,
        'latitude': latitude,
        'longitude': longitude

    }
)

print(ds)


<xarray.Dataset> Size: 456B
Dimensions:        (time: 4, latitude: 3, longitude: 2)
Coordinates:
  * time           (time) datetime64[ns] 32B 2023-01-01 ... 2023-01-04
  * latitude       (latitude) float64 24B -90.0 0.0 90.0
  * longitude      (longitude) float64 16B -180.0 180.0
Data variables:
    temperature    (time, latitude, longitude) float64 192B 0.2591 ... 0.4695
    precipitation  (time, latitude, longitude) float64 192B 0.5256 ... 0.6698


In [24]:
s=ds.sel(
    time='2023-01-02',
    latitude=-90,
    longitude=180
)

In [34]:
print(s.values())

ValuesView(<xarray.Dataset> Size: 40B
Dimensions:        ()
Coordinates:
    time           datetime64[ns] 8B 2023-01-02
    latitude       float64 8B -90.0
    longitude      float64 8B 180.0
Data variables:
    temperature    float64 8B 0.2155
    precipitation  float64 8B 0.9456)


In [37]:
type(s.values()).temperature

AttributeError: type object 'ValuesView' has no attribute 'temperature'

In [22]:
ds

<xarray.Dataset> Size: 456B
Dimensions:        (time: 4, latitude: 3, longitude: 2)
Coordinates:
  * time           (time) datetime64[ns] 32B 2023-01-01 ... 2023-01-04
  * latitude       (latitude) float64 24B -90.0 0.0 90.0
  * longitude      (longitude) float64 16B -180.0 180.0
Data variables:
    temperature    (time, latitude, longitude) float64 192B 0.2591 ... 0.4695
    precipitation  (time, latitude, longitude) float64 192B 0.5256 ... 0.6698

In [17]:
pd.date_range('2023-01-01', periods=4)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04'], dtype='datetime64[ns]', freq='D')

In [14]:
dataset.sel(Layer='A', Row=1)

<xarray.Dataset> Size: 20B
Dimensions:  ()
Coordinates:
    Layer    <U1 4B 'A'
    Row      int64 8B 1
Data variables:
    Col1     float32 4B 0.7933
    Col2     uint16 2B 41488
    Col3     uint8 1B 88
    Col4     uint8 1B 240

In [ ]:
import xarray as xr
import numpy as np

# Create a 4D array with different data types
temperature = np.random.rand(3, 4, 2, 5)  # 4D array of shape (3, 4, 2, 5)

# Create an xarray Dataset with 4D data
ds = xr.Dataset(
    {
        'var1': (['dim1', 'dim2', 'dim3', 'dim4'], temperature),
        'var2': (['dim1', 'dim2', 'dim3', 'dim4'], np.random.rand(3, 4, 2, 5))
    },
    coords={
        'dim1': ['A', 'B', 'C'],
        'dim2': ['X', 'Y', 'Z', 'W'],
        'dim3': ['one', 'two'],
        'dim4': [1, 2, 3, 4, 5]
    }
)

print(ds)


<xarray.Dataset> Size: 2kB
Dimensions:  (dim1: 3, dim2: 4, dim3: 2, dim4: 5)
Coordinates:
  * dim1     (dim1) <U1 12B 'A' 'B' 'C'
  * dim2     (dim2) <U1 16B 'X' 'Y' 'Z' 'W'
  * dim3     (dim3) <U3 24B 'one' 'two'
  * dim4     (dim4) int64 40B 1 2 3 4 5
Data variables:
    var1     (dim1, dim2, dim3, dim4) float64 960B 0.3439 0.9241 ... 0.6159
    var2     (dim1, dim2, dim3, dim4) float64 960B 0.6687 0.9485 ... 0.3778


In [40]:
import numpy as np

# Define dimensions
N, M, P = 4, 3, 2  # Example dimensions
# T is int32, float64 and str
# Create a structured 4D array (N, M, P, T)
dtype = np.dtype([
    ('int_field', 'int32'),
    ('float_field', 'float64'),
    ('str_field', 'U1')
])

# Create the array using dtype
table = np.empty((N, M, P), dtype=dtype)

# Populate the table with example data (random integers, floats, and strings)
table['int_field'] = np.random.randint(0, 100, (N, M, P))
table['float_field'] = np.random.random((N, M, P)) * 100
table['str_field'] = np.random.choice(['A', 'B', 'C', 'D'], (N, M, P))




In [69]:
arr = np.random.random((1000,))
arr

array([0.96669563, 0.37431093, 0.66678817, 0.51527279, 0.12112026,
       0.83376917, 0.47017636, 0.42620893, 0.8585076 , 0.54126888,
       0.944283  , 0.80204068, 0.94875093, 0.10371078, 0.41633057,
       0.19227696, 0.2010361 , 0.24656739, 0.30888939, 0.74175849,
       0.35423371, 0.84165115, 0.34038466, 0.23291975, 0.58132857,
       0.1521515 , 0.97812698, 0.93183478, 0.57512959, 0.42062211,
       0.42085813, 0.01051752, 0.29156365, 0.42857997, 0.20915913,
       0.79927334, 0.54171455, 0.21764741, 0.69066864, 0.90128028,
       0.95405306, 0.94598507, 0.33936265, 0.25317462, 0.05635391,
       0.8924749 , 0.5112457 , 0.66391037, 0.12562668, 0.83428418,
       0.72440106, 0.15995136, 0.48481717, 0.78591214, 0.3822733 ,
       0.43487594, 0.58642479, 0.02375489, 0.94504037, 0.57232496,
       0.54825545, 0.17499473, 0.38418095, 0.9484117 , 0.54686807,
       0.75233793, 0.75664566, 0.9961347 , 0.99640333, 0.48221432,
       0.07128358, 0.37397925, 0.0076628 , 0.92923237, 0.29286

In [70]:
def custom_func(x):
    return x**2 + 1

vec_func = np.vectorize(custom_func)



In [ ]:
%timeit arr2 = vec_func(arr) # 165 ys
arr2[:5]

165 μs ± 763 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


array([1.93450045, 1.14010867, 1.44460647, 1.26550605, 1.01467012])

In [ ]:
%timeit arr2 = [custom_func(x) for x in arr] # 164 ys
arr2[:5]

164 μs ± 595 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


array([1.93450045, 1.14010867, 1.44460647, 1.26550605, 1.01467012])

In [77]:
import pandas as pd
s=pd.Series(arr)
s

0      0.966696
1      0.374311
2      0.666788
3      0.515273
4      0.121120
         ...   
995    0.648142
996    0.310771
997    0.739701
998    0.775615
999    0.652026
Length: 1000, dtype: float64

In [ ]:
%timeit s.apply(custom_func) # 222 ys

222 μs ± 1.01 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [ ]:
%timeit list(map(custom_func, arr)) # 179 ys

179 μs ± 3.57 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [ ]:
%timeit list(map(custom_func, l)) # 154 ys

154 μs ± 402 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [83]:
l=list(arr)
l

[np.float64(0.9666956341526953),
 np.float64(0.37431093082539413),
 np.float64(0.6667881738538843),
 np.float64(0.5152727946480119),
 np.float64(0.12112025986820096),
 np.float64(0.8337691694120659),
 np.float64(0.47017636454507894),
 np.float64(0.4262089335511917),
 np.float64(0.8585076049478664),
 np.float64(0.5412688801687139),
 np.float64(0.9442830001397596),
 np.float64(0.8020406820313858),
 np.float64(0.9487509317081368),
 np.float64(0.10371078363447805),
 np.float64(0.4163305739707913),
 np.float64(0.19227696407206818),
 np.float64(0.20103610281724626),
 np.float64(0.24656739366449076),
 np.float64(0.3088893940730487),
 np.float64(0.7417584915413268),
 np.float64(0.35423370916566643),
 np.float64(0.841651148087576),
 np.float64(0.34038465631468895),
 np.float64(0.23291974572226415),
 np.float64(0.5813285737408301),
 np.float64(0.15215150175171466),
 np.float64(0.9781269811474239),
 np.float64(0.9318347788370229),
 np.float64(0.5751295859445525),
 np.float64(0.4206221095404683),


In [48]:
import pandas as pd

table[0,0]
# Convert the 1D structured array to a pandas DataFrame for better display
pd.DataFrame(table[0,0])

int_field  float_field str_field
0         47    83.806942         A
1          2    18.389918         C

In [56]:
l=table["int_field"][:,0,0]
l[1]=99

In [57]:
table["int_field"][:,0,0]

array([ 1, 99,  3,  4], dtype=int32)